xflags::xflags! {
    src "./src/flags.rs"

    /// Run custom build command
    cmd xtask {
        default cmd help {
            /// Print help information
            optional -h, --help
        }

        /// Clean $CARGO_TARGET of workspace-local artifacts
        cmd clean {}

        /// Regenerate nuts & bolts of generated code (automatically done by `cargo test`)
        cmd codegen {
            /// Regenerate syntax types (ast, etc)
            optional -s, --syntax
            /// Regenerate all generated code
            optional -a, --all
        }
    }
}

// generated start
// The following code is generated by `xflags` macro.
// Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
#[derive(Debug)]
pub struct Xtask {
    pub subcommand: XtaskCmd,
}

#[derive(Debug)]
pub enum XtaskCmd {
    Help(Help),
    Clean(Clean),
    Codegen(Codegen),
}

#[derive(Debug)]
pub struct Help {
    pub help: bool,
}

#[derive(Debug)]
pub struct Clean;

#[derive(Debug)]
pub struct Codegen {
    pub syntax: bool,
    pub all: bool,
}

impl Xtask {
    pub const HELP: &'static str = Self::HELP_;

    pub fn from_env() -> xflags::Result<Self> {
        Self::from_env_()
    }

    pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
        Self::from_vec_(args)
    }
}
// generated end
